/**
 * Single source of truth for action parameters.
 * Each action defines its params shape and whether it can contain child steps.
 */

const actionSchemas = {
  homepage_interaction: {
    description: 'Navigate to Facebook homepage / news feed',
    params: {},
    hasChildren: true,
  },
  scroll: {
    description:
      'Scroll the current page for a duration with human-like behavior. Provide `duration` for a fixed scroll, or `min`+`max` for a random duration in that range. `duration` wins if both are set. Defaults to 10s.',
    params: {
      duration: {
        type: 'number',
        description: 'Fixed seconds to scroll. Wins over min/max when set.',
      },
      min: {
        type: 'number',
        description: 'Lower bound (seconds) for random scroll. Pair with max.',
      },
      max: {
        type: 'number',
        description: 'Upper bound (seconds) for random scroll. Pair with min.',
      },
      direction: {
        type: 'string',
        default: 'down',
        enum: ['down', 'up'],
        description: 'Scroll direction',
      },
    },
    hasChildren: false,
  },
  like_posts: {
    description: 'Like posts on the current page (scroll first to load posts)',
    params: {
      count: { type: 'number', default: 2, description: 'Number of posts to like' },
      mode: {
        type: 'string',
        default: 'fixed',
        enum: ['fixed', 'half'],
        description: 'fixed=use count, half=like ~50% of found posts',
      },
    },
    hasChildren: false,
  },
  share_posts: {
    description:
      'Share posts from the current page. Provide message for static text, or userIdentity + instruction for Claude API-generated message (fallback: empty).',
    params: {
      count: { type: 'number', default: 1, description: 'Number of posts to share' },
      message: {
        type: 'string',
        default: '',
        description: 'Static message to include with share (overrides API generation)',
      },
      userIdentity: {
        type: 'string',
        default: '',
        description: 'Who the account is (used for API generation)',
      },
      instruction: {
        type: 'string',
        default: '',
        description: 'Tone/style instruction for API generation',
      },
    },
    hasChildren: false,
  },
  share_post: {
    description:
      'Share a specific Facebook post by URL. Provide message for static text, or userIdentity + instruction for Claude API-generated message.',
    params: {
      url: { type: 'string', description: 'Full URL of the Facebook post to share' },
      message: {
        type: 'string',
        default: '',
        description: 'Static message (overrides API generation)',
      },
      userIdentity: {
        type: 'string',
        default: '',
        description: 'Who the account is (used for API generation)',
      },
      instruction: {
        type: 'string',
        default: '',
        description: 'Tone/style instruction for API generation',
      },
    },
    hasChildren: false,
  },
  publish_post: {
    description:
      "Leaf: publish a new post (one or more images + AI-generated caption) to the user's own profile timeline. Navigates to facebook.com/me, opens the composer, uploads images via setInputFiles on the dialog's hidden <input type=\"file\">, types the caption into the Lexical editor, and clicks Post. Captions are generated by generatePostCaption (Gemini, system_prompt_post.txt) from userIdentity + postContext — the 50-reasons fallback in the prompt handles vague/empty contexts. When `imageUrls` is omitted, auto-injects a random pick from user.posts[]; the picked entry's `context` seeds `postContext`. Caption priority: explicit `caption` param > AI-generated > empty.",
    params: {
      imageUrls: {
        type: 'array',
        default: [],
        description:
          'Image URLs to upload. Auto-injected from a random pick of user.posts[].images when omitted (filenames resolved through IMAGE_SERVER_BASE_URL).',
        items: { type: 'string' },
      },
      caption: {
        type: 'string',
        default: '',
        description:
          'Static caption — overrides AI generation. Use this to hardcode test text.',
      },
      userIdentity: {
        type: 'string',
        default: '',
        description:
          'Persona for AI caption generation. Auto-injected from user.identityPrompt when omitted.',
      },
      postContext: {
        type: 'string',
        default: '',
        description:
          'Short description of the images to anchor the AI caption. Auto-injected from the picked user.posts[].context when omitted. Vague/empty values trigger the prompt\'s 50-reasons fallback.',
      },
      audience: {
        type: 'string',
        default: 'public',
        enum: ['public', 'friends', 'only-me', 'skip'],
        description:
          'Audience for the post. "skip" leaves FB\'s current default untouched. Audience widget failures are non-fatal (warned, not thrown).',
      },
    },
    hasChildren: false,
  },
  setup_about: {
    description:
      'Fill in Facebook profile About section (bio, work, education, places, relationship). Self-navigates via /me — no profileUrl needed. On completion, PATCHes the user record with status="Active" and profileSetup=true.',
    params: {
      bio: { type: 'string', description: 'Profile bio / intro text' },
      city: { type: 'string', description: 'Current city' },
      hometown: { type: 'string', description: 'Hometown' },
      userId: {
        type: 'string',
        default: '',
        description:
          'User ID for the PATCH call that sets status=Active + profileSetup=true. Auto-injected from user._id when omitted.',
      },
      personal: {
        type: 'object',
        description: 'Personal details',
        properties: {
          relationshipStatus: { type: 'string' },
          relationshipStatusSince: { type: 'string' },
          languages: { type: 'array', items: { type: 'string' } },
        },
      },
      work: {
        type: 'array',
        description: 'Work history entries',
        items: {
          type: 'object',
          properties: {
            company: { type: 'string' },
            position: { type: 'string' },
            from: { type: 'string' },
            to: { type: 'string' },
            current: { type: 'boolean' },
            city: { type: 'string' },
          },
        },
      },
      education: {
        type: 'object',
        description: 'Education history',
        properties: {
          college: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              from: { type: 'string' },
              to: { type: 'string' },
              graduated: { type: 'boolean' },
              degree: { type: 'string' },
            },
          },
          highSchool: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              from: { type: 'string' },
              to: { type: 'string' },
              graduated: { type: 'boolean' },
            },
          },
        },
      },
    },
    hasChildren: false,
  },
  visit_profile: {
    description:
      'Navigate to a Facebook profile/page by URL. Use child steps to act on the target. Provide url OR pool (random pick from config pool file).',
    params: {
      url: {
        type: 'string',
        description: 'Full Facebook profile/page URL. Wins over pool when both set.',
      },
      pool: {
        type: 'string',
        enum: ['friends', 'sharers', 'users'],
        description:
          'Random pick from a named pool: "friends" → config/friend_targets.json, "sharers" → config/share_sources.json, "users" → live DB fetch (5 random Active profiles with non-empty profileUrl)',
      },
    },
    hasChildren: true,
  },
  add_friend: {
    description:
      'Send a friend request on the currently loaded profile page. Use as a child step under visit_profile.',
    params: {},
    hasChildren: false,
  },
  setup_cover: {
    description: 'Upload a cover photo from a URL. Self-navigates to /me — no profileUrl needed.',
    params: {
      photoUrl: { type: 'string', description: 'Public URL of the image to upload as cover photo' },
    },
    hasChildren: false,
  },
  setup_avatar: {
    description:
      'Upload a profile picture from a URL. Probes the current page for the "Profile picture actions" trigger; navigates to /me only on miss. Caption priority: explicit description → AI-generated from userIdentity → random Bible verse fallback.',
    params: {
      photoUrl: {
        type: 'string',
        description: 'Public URL of the image to upload as profile picture',
      },
      description: {
        type: 'string',
        default: '',
        description: 'Explicit caption — overrides AI generation when provided.',
      },
      userIdentity: {
        type: 'string',
        default: '',
        description:
          'Persona POV for AI caption. Auto-injected from user.identityPrompt when omitted.',
      },
    },
    hasChildren: false,
  },
  create_page: {
    description:
      'Navigator: create a Facebook Page, fill all form fields, upload profile + cover, and advance through Steps 2-5. Ends on the new Page URL so child steps (schedule_posts, switch_profile) can run on it.',
    params: {
      pageName: { type: 'string', description: 'Page name to create' },
      bio: { type: 'string', default: '', description: 'Bio/description for the page' },
      email: { type: 'string', default: '', description: 'Contact email for the page' },
      streetAddress: {
        type: 'string',
        default: '',
        description: 'Street-only address for the page',
      },
      city: {
        type: 'string',
        default: '',
        description: 'Full city/state string, e.g. "Dallas, Texas"',
      },
      state: {
        type: 'string',
        default: '',
        description: 'State name. Auto-derived from city when omitted.',
      },
      zipCode: {
        type: 'string',
        default: '',
        description: 'ZIP code. Uses user.zip_code if present, otherwise a local seed dataset.',
      },
      profilePhotoUrl: {
        type: 'string',
        default: '',
        description: 'Profile image URL for the page',
      },
      coverPhotoUrl: { type: 'string', default: '', description: 'Cover image URL for the page' },
      categoryKeyword: {
        type: 'string',
        default: '',
        description: 'Optional category keyword. Defaults to the first word of pageName.',
      },
      userId: {
        type: 'string',
        default: '',
        description:
          'User ID for the PATCH call that records the new page URL. Auto-injected from user._id when omitted.',
      },
      pageUrl: {
        type: 'string',
        default: '',
        description:
          'Duplicate-Page guard. When non-empty, the action returns immediately without touching FB — protects against creating a second Page on accounts that already have one. Auto-injected from user.pageUrl. Pass an explicit empty string to override and force re-creation.',
      },
    },
    hasChildren: true,
  },
  schedule_posts: {
    description:
      'Schedule posts on the currently loaded Facebook Page — one post per day starting tomorrow. Individual post failures are logged, not rethrown.',
    params: {
      posts: {
        type: 'array',
        description: 'Posts to schedule. Auto-injected from user.linkedPage.posts when omitted.',
        items: {
          type: 'object',
          properties: {
            post: { type: 'string', description: 'Post text content' },
          },
        },
      },
    },
    hasChildren: false,
  },
  switch_profile: {
    description:
      'Switch back to the personal user profile from a Page. Falls back to "Quick switch profiles" when the named button is missing.',
    params: {
      userName: {
        type: 'string',
        default: '',
        description:
          'Full name on the personal profile. Auto-injected from user firstName + lastName when omitted.',
      },
    },
    hasChildren: false,
  },
  search: {
    description:
      'Navigator: search Facebook. Provide explicit `query`, or auto-generate — mode="name" (random first + last from 100×100 pools), mode="news" (random US state + news keyword), or mode="page" ("{category} in {city}" — city auto-injected from user.city). Optional `filter` clicks a results tab. Use child steps to act on the results.',
    params: {
      query: {
        type: 'string',
        default: '',
        description: 'Explicit search query. Overrides mode-based generation when provided.',
      },
      mode: {
        type: 'string',
        default: 'name',
        enum: ['name', 'news', 'page'],
        description: 'How to generate a query when `query` is empty',
      },
      filter: {
        type: 'string',
        default: '',
        description:
          'Optional results-tab filter to click after search (e.g. "People", "Posts", "Videos", "Pages", "Groups")',
      },
      category: {
        type: 'string',
        default: '',
        description:
          'Page-mode category override (e.g. "Photography"). Random from built-in pool when omitted.',
      },
      city: {
        type: 'string',
        default: '',
        description:
          'Page-mode city override (e.g. "Los Angeles, California"). Auto-injected from user.city when omitted.',
      },
    },
    hasChildren: true,
  },
  open_search_result: {
    description:
      'Navigator: pick a profile/page link from the current search-results page (a[href*="/profile.php?id="]) and click into it. Use as a child of `search`; child steps then act on that profile/page.',
    params: {
      pick: {
        type: 'string',
        default: 'random',
        description:
          'Which result to open: "random" (default), "first", or an integer index (0-based)',
      },
    },
    hasChildren: true,
  },
  follow: {
    description:
      'Leaf: click the Follow button on the currently loaded page. Selector is the same on profiles, pages, and inline search-result cards.',
    params: {},
    hasChildren: false,
  },
  connect: {
    description:
      'Leaf: click every "Add Friend" / "Follow" / "Like" button that is visible on the loaded profile or page, in that priority order. Add Friend matches any aria-label starting with "Add Friend" (dynamic name suffix); Follow and Like match their exact aria-label so already-followed / already-liked states do not re-click. Never throws if none are visible — logs and skips.',
    params: {},
    hasChildren: false,
  },
  connect_loop: {
    description:
      'Loop: visit random profiles from a pool and click "Add friend" until N successful presses, FB rate-limit modal, or maxAttempts. Increments only when the Add Friend button was actually pressed; profiles with no Add Friend button are skipped without counting. Stops immediately on the "You Cant Use This Feature Right Now" modal.',
    params: {
      pool: {
        type: 'string',
        default: 'users',
        enum: ['friends', 'sharers', 'users'],
        description: 'Random pick source — same as visit_profile pools',
      },
      count: {
        type: 'number',
        default: 7,
        description: 'Target number of successful Add Friend presses',
      },
      maxAttempts: {
        type: 'number',
        description: 'Safety cap on total iterations. Defaults to count*3.',
      },
      waitMin: {
        type: 'number',
        default: 30,
        description: 'Lower bound (seconds) for between-iteration wait',
      },
      waitMax: {
        type: 'number',
        default: 60,
        description: 'Upper bound (seconds) for between-iteration wait',
      },
      userId: {
        type: 'string',
        default: '',
        description:
          'Sender profile ID for the friend-request record posted on every successful Add friend press. Auto-injected from user._id when omitted.',
      },
      maxFriends: {
        type: 'number',
        default: 30,
        description:
          'Only used when pool="users". Filters candidates to profiles whose recorded friends count is below this threshold. Profiles with no recorded count are still included (their count gets PATCHed during the visit).',
      },
      skipIfFriendsAbove: {
        type: 'number',
        description:
          'Optional sender-side skip. When set, the action navigates to /me, reads the sender\'s own current friend count, PATCHes it back to the user record (keeps the DB fresh — sender friend count is otherwise only updated when another bot visits this profile), and if the count exceeds this threshold returns without running the loop. Omit to never skip.',
      },
    },
    hasChildren: false,
  },
  accept_loop: {
    description:
      'Walk the current profile\'s pending incoming friend requests (user.friendRequests where status="Pending"), visit each sender\'s profile, click "Confirm request", and PATCH the record to status="Accepted". Source list is fetched fresh at action start.',
    params: {
      waitMin: {
        type: 'number',
        default: 30,
        description: 'Lower bound (seconds) for between-iteration wait',
      },
      waitMax: {
        type: 'number',
        default: 60,
        description: 'Upper bound (seconds) for between-iteration wait',
      },
      userId: {
        type: 'string',
        default: '',
        description:
          'Receiver profile ID — the current browser\'s user. Auto-injected from user._id when omitted.',
      },
    },
    hasChildren: false,
  },
  check_ip: {
    description:
      "Fetch the browser's outbound IP from ipinfo.io (via the profile's proxy, not the host network) and POST it to the database. Runs automatically at the start of every browser session; can also be composed as a step.",
    params: {
      userId: {
        type: 'string',
        default: '',
        description:
          'User ID to attach the IP record to. Auto-injected from user._id when omitted.',
      },
      endpoint: {
        type: 'string',
        default: '',
        description:
          'Override POST endpoint. Defaults to IP_LOG_ENDPOINT env, then USER_API_BASE_URL + /api/profiles/:userId/ip-records.',
      },
    },
    hasChildren: false,
  },
  outlook_login: {
    description:
      'Leaf: sign into outlook.com using the email + password on the user record. Navigates to outlook.live.com (single tab — Microsoft auth handles the redirect), fills email/password, and walks every post-login prompt (passkey, "Stay signed in?", "Protect your account") until the inbox loads. Credentials auto-injected from user.emails[selected].address and user.emailPassword.',
    params: {
      email: {
        type: 'string',
        default: '',
        description:
          'Outlook/Microsoft account email. Auto-injected from user.emails (selected, or [0]) when omitted.',
      },
      password: {
        type: 'string',
        default: '',
        description: 'Outlook/Microsoft account password. Auto-injected from user.emailPassword when omitted.',
      },
    },
    hasChildren: false,
  },
  facebook_signup: {
    description:
      'Leaf: sign up for a new Facebook account from the logged-out homepage. Navigates to facebook.com if not already there, clicks "Create new account", fills First/Last name, picks Month/Day/Year/Gender, fills email + password, clicks Submit, then waits for the Home button (href="/") to appear (up to 5 min) as the success signal. After login, navigates to /settings/bundled and walks the post-signup Public → Next → Confirm acknowledgment. On success, PATCHes the user record with status="Need Setup" so the next batch picks the profile up for setup_about / setup_avatar / setup_cover. All credentials auto-injected from the user record.',
    params: {
      userId: {
        type: 'string',
        default: '',
        description:
          'User ID for the post-signup status PATCH. Auto-injected from user._id when omitted.',
      },
      firstName: {
        type: 'string',
        default: '',
        description: 'First name. Auto-injected from user.firstName when omitted.',
      },
      lastName: {
        type: 'string',
        default: '',
        description: 'Last name. Auto-injected from user.lastName when omitted.',
      },
      birthdayDate: {
        type: 'string',
        default: '',
        description:
          'Date of birth. Auto-injected from user.birthdayDate (fallback: user.dob) when omitted.',
      },
      gender: {
        type: 'string',
        default: '',
        description: 'Gender. Auto-injected from user.gender when omitted.',
      },
      email: {
        type: 'string',
        default: '',
        description:
          'Email address. Auto-injected from user.emails (selected, or [0]) when omitted.',
      },
      password: {
        type: 'string',
        default: '',
        description: 'Facebook password. Auto-injected from user.facebookPassword when omitted.',
      },
    },
    hasChildren: false,
  },
  ensure_login: {
    description:
      'Leaf: re-login when the session has been logged out. Detection signals: URL match (/login), visible input[name="pass"], or profile probe via user.profileUrl (if final URL contains /people/ or pfbid, session is browsing as guest). Re-auth navigates to https://web.facebook.com/reg/?entry_point=login&next= and re-runs the signup form fill — facebook_signup is called with skipPostSetup=true so it returns once the home href appears (no /settings/bundled walk, no status PATCH). Runner auto-invokes this at session start when isLoggedOut() returns true. All signup params auto-injected from the user record.',
    params: {
      firstName: {
        type: 'string',
        default: '',
        description: 'First name. Auto-injected from user.firstName when omitted.',
      },
      lastName: {
        type: 'string',
        default: '',
        description: 'Last name. Auto-injected from user.lastName when omitted.',
      },
      birthdayDate: {
        type: 'string',
        default: '',
        description:
          'Date of birth. Auto-injected from user.birthdayDate (fallback: user.dob) when omitted.',
      },
      gender: {
        type: 'string',
        default: '',
        description: 'Gender. Auto-injected from user.gender when omitted.',
      },
      email: {
        type: 'string',
        default: '',
        description:
          'Facebook account email. Auto-injected from user.emails (selected, or [0]) when omitted.',
      },
      password: {
        type: 'string',
        default: '',
        description: 'Facebook password. Auto-injected from user.facebookPassword when omitted.',
      },
      skipPostSetup: {
        type: 'boolean',
        default: false,
        description:
          'When true, return as soon as the home href appears — skip the /settings/bundled walk and the status PATCH. Used by ensure_login when re-running the signup form purely as a re-login mechanism.',
      },
    },
    hasChildren: false,
  },
  facebook_login: {
    description:
      'Leaf: sign into an existing Facebook account from the logged-out homepage. Fills #login_form (email + password), presses Enter, dismisses the "Save your login info?" prompt, and waits for the Home button (href="/") to confirm. Credentials auto-injected from user.emails (selected, or [0]) and user.facebookPassword.',
    params: {
      email: {
        type: 'string',
        default: '',
        description:
          'Facebook account email. Auto-injected from user.emails (selected, or [0]) when omitted.',
      },
      password: {
        type: 'string',
        default: '',
        description: 'Facebook password. Auto-injected from user.facebookPassword when omitted.',
      },
    },
    hasChildren: false,
  },
  wait: {
    description:
      'Idle on the current page for a duration in seconds. Provide `duration` for a fixed wait, or `min`+`max` for a random wait in that range. `duration` wins if both are set. Defaults to 5s.',
    params: {
      duration: {
        type: 'number',
        description: 'Fixed wait in seconds. Wins over min/max when set.',
      },
      min: { type: 'number', description: 'Lower bound (seconds) for random wait. Pair with max.' },
      max: { type: 'number', description: 'Upper bound (seconds) for random wait. Pair with min.' },
    },
    hasChildren: false,
  },
};

module.exports = actionSchemas;
